# params used in the paper for trillion transitions experiment.
# params optimized for 8xA100 GPU node
env_id: "XLand-MiniGrid-R4-13x13"
benchmark_id: "high-1m"
total_timesteps: 1_000_000_000_000
num_envs: 131072
num_steps_per_env: 12800
num_steps_per_update: 256
update_epochs: 1
num_minibatches: 32
eval_num_envs: 16384
eval_num_episodes: 25
train_seed: 5