# params used in the paper for meta-RL experiments. Overwrite default benchmark_id if needed.
env_id: "XLand-MiniGrid-R4-13x13"
benchmark_id: "high-1m"
total_timesteps: 10_000_000_000
num_envs: 16384
num_steps_per_env: 12800
num_steps_per_update: 256
update_epochs: 1
num_minibatches: 16
eval_num_envs: 16384
eval_num_episodes: 25
train_seed: 5